name: ytdl-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev # For alsa/asoundlib.h header needed for npm install

    - name: npm install, build and test
      run: |
        npm install
        npm run build
        npm test
