name: ytdl-publish

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - run: git fetch --all --tags
        
      - name: Check version change
        uses: thebongy/version-check@v1
        id: check
        with:
          file: package.json
          failBuild: false
          tagFormat: v${version}
      
      - name: Echo variables
        run: |
          echo "versionChanged- ${{steps.check.outputs.versionChanged}}"
          echo "releaseVersion- ${{steps.check.outputs.releaseVersion}}"
      
      - run: |
          sudo apt-get update
          sudo apt-get install libasound2-dev # For alsa/asoundlib.h header needed for npm install

      - if: steps.check.outputs.versionChanged == 'true'
        run: npm install

      - if: steps.check.outputs.versionChanged == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
